site_name: WarZipern's Notes✨✨

repo_url: https://github.com/Anwangyu

# repo_name: 'Anwangyu/anwangyu.github.io'

site_author: WarZipern
              
site_description: WarZipern's Notes



markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
theme: 
  name: material
  palette: 
    primary: 'indigo'
    accent: 'deep orange'
  favicon: images/favicon.png


  features: 
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - toc.follow
    - navigation.top
  language: 'en' 

# markdown_extensions:
#   - abbr
#   - admonition
#   - attr_list
#   - def_list
#   - footnotes
#   - md_in_html
#   - toc:
#       permalink: true
#   - pymdownx.arithmatex:
#       generic: true
#   - pymdownx.betterem:
#       smart_enable: all
#   - pymdownx.caret
#   - pymdownx.details
#   - pymdownx.emoji:
#       emoji_generator: !!python/name:material.extensions.emoji.to_svg
#       emoji_index: !!python/name:material.extensions.emoji.twemoji
#   - pymdownx.highlight:
#       anchor_linenums: true
#       line_spans: __span
#       pygments_lang_class: true
#   - pymdownx.inlinehilite
#   - pymdownx.keys
#   - pymdownx.magiclink:
#       normalize_issue_symbols: true
#       repo_url_shorthand: true
#       user: squidfunk
#       repo: mkdocs-material
#   - pymdownx.mark
#   - pymdownx.smartsymbols
#   - pymdownx.snippets:
#       auto_append:
#         - includes/mkdocs.md
#   - pymdownx.superfences:
#       custom_fences:
#         - name: mermaid
#           class: mermaid
#           format: !!python/name:pymdownx.superfences.fence_code_format
#   - pymdownx.tabbed:
#       alternate_style: true
#       combine_header_slug: true
#       slugify: !!python/object/apply:pymdownx.slugs.slugify
#         kwds:
#           case: lower
#   - pymdownx.tasklist:
#       custom_checkbox: true
#   - pymdownx.tilde

extra_javascript:
  - js/katex.min.js
  - js/mathtex-script-type.min.js
  - js/copy-tex.min.js
  - js/auto-render.min.js
  - js/jquery-3.6.0.min.js # 使用最新的jQuery版本
  - js/d3.v7.min.js # 更新D3.js到最新版本
  - js/d3-flextree.js
  - js/view.mindmap.js
  - js/emoji.min.js 
  - js/mermaid.min.js 
  - js/highlight.pack.js 
  - js/extra.js 
  - js/readingtime.js 

extra_css:
  - css/katex.min.css
  - css/copy-tex.min.css
  - css/view.mindmap.css
  - css/atom-one-dark-reasonable.css 
  - css/font-awesome-all.min.css 
  - css/emoji.css 
  - css/extra.css
  - css/custom.css  # 引入自定义 CSS

